[tool.poetry]
name = "andotp-decrypt"
version = "0.1.7"
description = "A backup decryptor for the andOTP Android app"
authors = ["asmw <asmw@asmw.org>"]
readme = "README.md"
homepage = "https://github.com/asmw/andOTP-decrypt"
license = "MIT"
packages = [
    { include = "andotp_decrypt.py" },
    { include = "generate_code.py" },
    { include = "generate_qr_codes.py" },
]

[tool.poetry.scripts]
andotp_decrypt = 'andotp_decrypt:main'
andotp_gencode = 'generate_code:main'
andotp_qrcode = 'generate_qr_codes:main'

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
pyotp = "^2.3.0"
pycryptodome = "^3.9.4"
docopt-ng = "^0.9"
pyqrcode = "^1.2.1"

[tool.poetry.group.dev.dependencies]
rope = "^1.13"
pylint = "^3.3"
flake8 = "^7.1"
pytest = "^8.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
